spring.application.name=istikbal

# Database Configuration (PostgreSQL for local development)
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=istikbal
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Emre541523.

# Hibernate JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Disable H2 Console (Not needed for PostgreSQL)
spring.h2.console.enabled=false

# JWT Settings

# Secret Key must be at least 256 bits (32 bytes) long. Below is a 256-bit hex-encoded secret key.
application.security.jwt.secret-key=407F4E645267556B58703273357638792F423F4528482B4D6251655468576D5A
# Token expiration time: 86400000 ms (24 hours)
application.security.jwt.expiration=86400000

# Excel File Path Settings
app.excel.file-path=/Users/emresahin/Desktop/proje/SAP Extract Report.xlsx

# Server configuration
server.port=8080

# Multipart File Upload Settings (Up to 100MB for large Excel files)
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# n8n Webhook Target URL
n8n.webhook.url=http://localhost:5678/webhook-test/api/mail/send
n8n.ai.webhook.url=http://localhost:5678/webhook-test/api/ai/analyze

